[[local|localrc]]
GIT_BASE=https://github.com
HOST_IP=10.1.0.2
HOST_NAME=cmp2
SERVICE_HOST_NAME=ctrlnet-cmp1
SERVICE_HOST=10.1.0.1
MULTI_HOST=1
RECLONE=Yes
OFFLINE=Yes

#IMAGE_URLS+="http://launchpad.net/cirros/trunk/0.3.2/+download/cirros-0.3.2-x86_64-uec.tar.gz,http://berrange.fedorapeople.org/images/2012-02-29/f16-x86_64-openstack-sda.qcow2"
#IMAGE_URLS+="https://cloud-images.ubuntu.com/releases/14.04/release/ubuntu-14.04-server-cloudimg-arm64-disk1.img"

MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
KEYSTONE_AUTH_HOST=$SERVICE_HOST
KEYSTONE_SERVICE_HOST=$SERVICE_HOST
ADMIN_PASSWORD=password
MYSQL_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=tokennekot

SCREEN_LOGDIR=$DEST/logs/screen
LOGFILE=$DEST/logs/stack.sh.log
#LOG_COLOR=False

#FLOATING_RANGE=192.168.57.128/25
#PUBLIC_NETWORK_GATEWAY=192.168.56.1
#FLAT_INTERFACE=eth2

NEUTRON_CREATE_INITIAL_NETWORKS=True
Q_PLUGIN=ml2
ENABLE_TENANT_TUNNELS=True
#Q_ML2_TENANT_NETWORK_TYPE=vxlan
enable_plugin networking-odl https://github.com/stackforge/networking-odl

VNCSERVER_PROXYCLIENT_ADDRESS=$HOST_IP
VNCSERVER_LISTEN=0.0.0.0

ENABLED_SERVICES=n-cpu,n-net,n-api,nova
NOVA_VNC_ENABLED=True

ODL_MODE=compute
#ODL_PROVIDER_MAPPINGS=physnet1:eth1

#ODL_LOCAL_IP=192.168.56.101
#ODL_MGR_IP=127.0.0.1
ODL_MGR_IP=10.1.0.3

# Port for rest calls
ODL_PORT=8080

#Port for OVSDB
#ODL_MGR_PORT=6640

[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[agent]
minimize_polling=True

